vector-store:
  lancedb:
    resume-store:
      path: "data/sample-lancedb"
      table-name: "resume"
      schema: ResumeSchema

    info-store:
      path: "data/sample-lancedb"
      table-name: "info"
      schema: InfoSchema

store:
  postgres:
    user-store:
      host: "your_database_host"
      port: your_database_port
      database: "your_database_name"
      user: "your_database_user"
      password: "your_secure_password"
      table-name: "users"
      schema: UserSchema

chat-model:
  model-name: "gpt-4"
  temperature: 0.0
  key: xxx
  cache: False

embeddings-model:
  name: "OpenAIEmbeddings"
  key: xxx
  
service:
  host: 0.0.0.0
  port: 9000
  workers: 5