service:
  host: 0.0.0.0
  port: 9000
  workers: 1
  data_path: "my-data"

vector-store:
  lancedb:
    resume-store:
      table-name: "resume"
      schema: ResumeSchema

    info-store:
      table-name: "info"
      schema: InfoSchema

store:
  postgres:
    user-store:
      host: localhost
      port: 5432
      database: applibot_db
      user: applibot_user
      password: change_this_password
      table-name: users
      schema: UserSchema

chat-model:
  model-name: "gpt-4"
  temperature: 0.0
  key: xxx
  cache: True

embeddings-model:
  name: "OpenAIEmbeddings"
  key: xxx
  cache: True