vector-store:
  lancedb:
    resume-store:
      path: "data/sample-lancedb"
      table-name: "resume"
      schema: ResumeSchema

    info-store:
      path: "data/sample-lancedb"
      table-name: "info"
      schema: InfoSchema

chat-model:
  model-name: "gpt-4"
  temperature: 0.0

embeddings-model:
  name: "OpenAIEmbeddings"

service:
  host: "0.0.0.0"
  port: 8000