service:
  host: 0.0.0.0
  port: 9000
  workers: 1
  data-path: my-data/
  secret-key: xxx
  hash-algorithm: HS256
  access-token-expire-minutes: 10000
  token-url: token
  pwd-context-schemes:
   - bcrypt
  pwd-context-depricated: auto
  
table-store:
  postgres:
   url: "postgresql://applibot_user:xxx@localhost/applibot_db"

vector-store:
  lancedb:
    info-store:
      table-name: info
      schema: InfoSchema

chat-model:
  model-name: gpt-4-1106-preview
  temperature: 0.0
  key: sk-xxx
  cache: True

embeddings-model:
  name: OpenAIEmbeddings
  key: sk-xxx
  cache: True